package security

import (
	"encoding/base64"
	"errors"
	"fmt"
	"math/rand"
	"strconv"
	"strings"
	"sync"
	"time"

	"golang.org/x/crypto/argon2"
	"crypto/subtle"
)

// Argon2idHasher implements PasswordHasher using argon2id.
type Argon2idHasher struct {
	memory      uint32
	iterations  uint32
	parallelism uint8
	saltLength  int
	keyLength   uint32
	rand        *rand.Rand
	mu          sync.Mutex
}

// NewArgon2idHasher creates a new Argon2id hasher with the given parameters.
// memory: memory usage in KiB.
// iterations: number of iterations to perform.
// parallelism: number of parallel threads to use.
// saltLength: length of the salt to use.
// keyLength: length of the generated key to use.
func NewArgon2idHasher(memory uint32, iterations uint32, parallelism uint8, saltLength int, keyLength uint32) *Argon2idHasher {
	return &Argon2idHasher{
		memory:      memory,
		iterations:  iterations,
		parallelism: parallelism,
		saltLength:  saltLength,
		keyLength:   keyLength,
		rand:        rand.New(rand.NewSource(time.Now().UnixNano())),
	}
}

// Hash generates an argon2id hash of the password.
// The returned string is in the format: $argon2id$v=19$m=<memory>,t=<iterations>,p=<parallelism>$<salt>$<hash>
// where salt and hash are base64 encoded.
func (h *Argon2idHasher) Hash(password string) (string, error) {
	// Generate a random salt
	salt := make([]byte, h.saltLength)
	h.mu.Lock()
	if _, err := h.rand.Read(salt); err != nil {
		h.mu.Unlock()
		return "", err
	}
	h.mu.Unlock()

	// Hash the password with argon2id
	hash := argon2.IDKey([]byte(password), salt, h.iterations, h.memory, h.parallelism, h.keyLength)

	// Encode salt and hash to base64
	saltB64 := base64.RawStdEncoding.EncodeToString(salt)
	hashB64 := base64.RawStdEncoding.EncodeToString(hash)

	// Return the formatted hash string
	return fmt.Sprintf("$argon2id$v=19$m=%d,t=%d,p=%d$%s$%s", h.memory, h.iterations, h.parallelism, saltB64, hashB64), nil
}

// Compare checks if the password matches the hash.
// Expects the hash to be in the format generated by Hash().
func (h *Argon2idHasher) Compare(hashPassword, password string) error {
	// Parse the hash string
	var memory, iterations uint32
	var parallelism uint8

	// Expected format: $argon2id$v=19$m=<memory>,t=<iterations>,p=<parallelism>$<salt>$<hash>
	if !strings.HasPrefix(hashPassword, "$argon2id$v=19$") {
		return errors.New("invalid hash format")
	}

	// Remove the prefix
	hashPassword = strings.TrimPrefix(hashPassword, "$argon2id$v=19$")

	// Split into parameters and the rest
	parts := strings.SplitN(hashPassword, "$", 2)
	if len(parts) != 2 {
		return errors.New("invalid hash format")
	}

	// Parse parameters: m=<memory>,t=<iterations>,p=<parallelism>
	paramsStr := parts[0]
	data := parts[1]

	for _, part := range strings.Split(paramsStr, ",") {
		keyValue := strings.SplitN(part, "=", 2)
		if len(keyValue) != 2 {
			continue
		}
		switch keyValue[0] {
		case "m":
			if v, err := strconv.ParseUint(keyValue[1], 10, 32); err == nil {
				memory = uint32(v)
			}
		case "t":
			if v, err := strconv.ParseUint(keyValue[1], 10, 32); err == nil {
				iterations = uint32(v)
			}
		case "p":
			if v, err := strconv.ParseUint(keyValue[1], 10, 8); err == nil {
				parallelism = uint8(v)
			}
		}
	}

	// Split data into salt and hash
	dataParts := strings.SplitN(data, "$", 2)
	if len(dataParts) != 2 {
		return errors.New("invalid hash format")
	}
	saltB64, hashB64 := dataParts[0], dataParts[1]

	// Decode salt and hash from base64
	saltDecoded, err := base64.RawStdEncoding.DecodeString(saltB64)
	if err != nil {
		return err
	}
	hashDecoded, err := base64.RawStdEncoding.DecodeString(hashB64)
	if err != nil {
		return err
	}

	// Set the salt length from the decoded salt (should match what was used in Hash)
	// (Not needed in Compare)

	// Hash the password with the same parameters
	computedHash := argon2.IDKey([]byte(password), saltDecoded, iterations, memory, parallelism, h.keyLength)

	// Compare the hashes using constant time comparison
	if subtle.ConstantTimeCompare(hashDecoded, computedHash) == 1 {
		return nil
	}
	return errors.New("password mismatch")
}